export const historyData = [
    {
      alertId: "AH-101",
      ruleName: "High CPU Usage",
      triggeredOn: "2025-03-10 14:30",
      status: "Resolved",
      actionTaken: "Increased server capacity",
      resolver: "John (Admin)",
    },
    {
      alertId: "AH-102",
      ruleName: "High CPU Usage",
      triggeredOn: "2025-03-10 14:30",
      status: "Resolved",
      actionTaken: "Increased server capacity",
      resolver: "John (Admin)",
    },
    {
      alertId: "AH-103",
      ruleName: "High CPU Usage",
      triggeredOn: "2025-03-10 14:30",
      status: "Resolved",
      actionTaken: "Increased server capacity",
      resolver: "John (Admin)",
    },
    {
      alertId: "AH-104",
      ruleName: "High CPU Usage",
      triggeredOn: "2025-03-10 14:30",
      status: "Resolved",
      actionTaken: "Increased server capacity",
      resolver: "John (Admin)",
    },
    {
      alertId: "AH-105",
      ruleName: "High CPU Usage",
      triggeredOn: "2025-03-10 14:30",
      status: "Resolved",
      actionTaken: "Increased server capacity",
      resolver: "John (Admin)",
    },
  ];

  export const rulesTableHeadings = [
    "Rule ID",
    "Rule Name",
    "Metric",
    "Threshold",
    "Duration",
    "Notification",
    "Recipient",
    "Actions",
  ];

  export const historyTableHeadings = [
    "Alert ID",
    "Rule Name",
    "Triggered On",
    "Status",
    "Action Taken",
    "Resolver",
  ];

 export const rulesData = [
    {
      ruleId: "AR-001",
      ruleName: "High CPU Usage",
      metric: "CPU Usage",
      threshold: "> 90%",
      duration: "10 minutes",
      notifications: "Email, In-App",
      recipient: "DevOps Team",
    },
    {
      ruleId: "AR-002",
      ruleName: "High CPU Usage",
      metric: "CPU Usage",
      threshold: "> 90%",
      duration: "10 minutes",
      notifications: "Email, In-App",
      recipient: "DevOps Team",
    },
    {
      ruleId: "AR-003",
      ruleName: "High CPU Usage",
      metric: "CPU Usage",
      threshold: "> 90%",
      duration: "10 minutes",
      notifications: "Email, In-App",
      recipient: "DevOps Team",
    },
    {
      ruleId: "AR-004",
      ruleName: "High CPU Usage",
      metric: "CPU Usage",
      threshold: "> 90%",
      duration: "10 minutes",
      notifications: "Email, In-App",
      recipient: "DevOps Team",
    },
    {
      ruleId: "AR-005",
      ruleName: "High CPU Usage",
      metric: "CPU Usage",
      threshold: "> 90%",
      duration: "10 minutes",
      notifications: "Email, In-App",
      recipient: "DevOps Team",
    },
    {
      ruleId: "AR-006",
      ruleName: "High CPU Usage",
      metric: "CPU Usage",
      threshold: "> 90%",
      duration: "10 minutes",
      notifications: "Email, In-App",
      recipient: "DevOps Team",
    },
    {
      ruleId: "AR-007",
      ruleName: "High CPU Usage",
      metric: "CPU Usage",
      threshold: "> 90%",
      duration: "10 minutes",
      notifications: "Email, In-App",
      recipient: "DevOps Team",
    },
  ]